return {
    Click = { url = "rbxassetid://4499400560"},
    Bonk = { url = "rbxassetid://6352582283"},
    Minecraft = { url = "rbxassetid://4018616850"},
    Neverlose = { url = "rbxassetid://6534948092"},
    Fatality = { url = "rbxassetid://6534947869"},
    Skeet = { url = "rbxassetid://5633695679"},
    Rust = { url = "rbxassetid://1255040462"},
    Pop = { url = "rbxassetid://198598793"},
    Bell = { url = "https://doitenroi.vercel.app/sound/bell.wav", customasset = true },
    Bubble = { url = "rbxassetid://6534947588"},
    Bruh = { url = "rbxassetid://4275842574"},
    UwU = { url = "rbxassetid://8323804973"},
    Hentai = { url = "https://doitenroi.vercel.app/sound/Hrntai.wav", customasset = true },
    Hentai2 = { url = "https://doitenroi.vercel.app/sound/henta01.wav", customasset = true },
    ["Among Us Kill"] = { url = "https://doitenroi.vercel.app/sound/amongus_kill.wav", customasset = true },
    ["Apple Pay"] = { url = "https://doitenroi.vercel.app/sound/applepay.wav", customasset = true },
    ["Mario Woahh"] = { url = "https://doitenroi.vercel.app/sound/mariowoahh.wav", customasset = true },
    Hentai3 = { url = "https://doitenroi.vercel.app/sound/hentai1.wav", customasset = true },
    Hentai4 = { url = "https://doitenroi.vercel.app/sound/hentai2.mp3", customasset = true },
    Hentai5 = { url = "https://doitenroi.vercel.app/sound/hentai3.mp3", customasset = true },
    Gamesense = { url = "rbxassetid://4817809188"},
    Bameware = { url = "rbxassetid://6565367558"},
    COD = { url = "rbxassetid://160432334"},
}
